# General Jekyll Config
highlighter: pygments.rb
url: https://justiceadamsuni.github.io
baseurl: /Math-Club-Website
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, vendor]